/**
 * MITRA AI — Database Population & Batch Seeding Engine
 * 
 * Ingests the synthetic dataset generated by scripts/generateDataset.js into MySQL.
 * Uses high-throughput chunked bulk inserts.
 */

const fs = require('fs');
const path = require('path');
try {
  require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
} catch (e) {
  try {
    require('../backend/node_modules/dotenv').config({ path: path.join(__dirname, '..', '.env') });
  } catch (err) {}
}
let mysql;
try {
  mysql = require('mysql2/promise');
} catch (e) {
  mysql = require('../backend/node_modules/mysql2/promise');
}

function formatVal(val) {
  if (val === undefined || val === null) return null;
  if (typeof val === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(val)) {
    return val.replace('T', ' ').replace('Z', '').split('.')[0];
  }
  return val;
}

async function chunkInsert(connection, tableName, columns, rows, chunkSize = 500) {
  if (!rows || rows.length === 0) return;
  const colSql = columns.map(c => `\`${c}\``).join(', ');
  
  for (let i = 0; i < rows.length; i += chunkSize) {
    const chunk = rows.slice(i, i + chunkSize);
    const placeholders = chunk.map(() => `(${columns.map(() => '?').join(', ')})`).join(', ');
    const flatValues = [];
    chunk.forEach(row => {
      columns.forEach(col => {
        flatValues.push(formatVal(row[col]));
      });
    });

    const sql = `INSERT IGNORE INTO \`${tableName}\` (${colSql}) VALUES ${placeholders}`;
    await connection.query(sql, flatValues);
  }
}

async function seedDatabase() {
  console.log('🚀 Initializing MITRA AI Database Seeder...');
  
  const datasetPath = path.join(__dirname, '..', 'data', 'processed', 'generated_dataset.json');
  if (!fs.existsSync(datasetPath)) {
    console.log('⚡ Generated dataset not found. Generating now via generateDataset.js...');
    require('./generateDataset');
  }

  const rawData = fs.readFileSync(datasetPath, 'utf8');
  const dataset = JSON.parse(rawData);

  const config = {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '3306', 10),
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || 'mitra_ai'
  };

  let connection;
  try {
    connection = await mysql.createConnection(config);
    console.log(`🔌 Connected to database [${config.database}]`);

    // Disable foreign key checks for fast bulk load
    await connection.query('SET FOREIGN_KEY_CHECKS = 0');

    // 1. Seed Products
    console.log(`📦 Seeding ${dataset.products.length} Products...`);
    const prodCols = ['id', 'merchant_id', 'category_id', 'supplier_id', 'sku', 'name', 'cost_price', 'selling_price', 'reorder_point', 'reorder_quantity', 'safety_stock', 'lead_time_days', 'status'];
    await chunkInsert(connection, 'products', prodCols, dataset.products);

    // 2. Seed Inventory
    console.log(`🏭 Seeding ${dataset.inventory.length} Inventory records...`);
    const invCols = ['id', 'merchant_id', 'product_id', 'warehouse_location', 'current_stock', 'reserved_stock', 'incoming_stock', 'damaged_stock'];
    await chunkInsert(connection, 'inventory', invCols, dataset.inventory);

    // 3. Seed Customers
    console.log(`👥 Seeding ${dataset.customers.length} Customers...`);
    const custCols = ['id', 'merchant_id', 'customer_code', 'first_name', 'last_name', 'email', 'phone', 'city', 'state', 'pincode', 'segment', 'total_orders_count', 'total_spend', 'first_order_date', 'last_order_date'];
    await chunkInsert(connection, 'customers', custCols, dataset.customers);

    // 4. Seed Orders
    console.log(`🛒 Seeding ${dataset.orders.length} Orders...`);
    const ordCols = ['id', 'merchant_id', 'customer_id', 'order_number', 'order_date', 'subtotal', 'discount_amount', 'tax_amount', 'shipping_amount', 'total_amount', 'status', 'shipping_city', 'shipping_state', 'shipping_pincode', 'carrier_name', 'tracking_number', 'delivery_status', 'promised_delivery_date', 'actual_delivery_date'];
    await chunkInsert(connection, 'orders', ordCols, dataset.orders);

    // 5. Seed Order Items
    console.log(`📋 Seeding ${dataset.order_items.length} Order Items...`);
    const oiCols = ['id', 'order_id', 'product_id', 'quantity', 'unit_price', 'unit_cost', 'total_price'];
    await chunkInsert(connection, 'order_items', oiCols, dataset.order_items);

    // 6. Seed Payments
    console.log(`💳 Seeding ${dataset.payments.length} Payments...`);
    const payCols = ['id', 'merchant_id', 'order_id', 'customer_id', 'gateway', 'gateway_order_id', 'gateway_payment_id', 'amount', 'currency', 'status', 'failure_reason', 'error_code', 'error_description', 'payment_method', 'retry_count', 'initiated_at', 'completed_at'];
    await chunkInsert(connection, 'payments', payCols, dataset.payments);

    // 7. Seed Refunds
    console.log(`🔄 Seeding ${dataset.refunds.length} Refunds...`);
    const refCols = ['id', 'merchant_id', 'payment_id', 'order_id', 'gateway_refund_id', 'amount', 'currency', 'reason_code', 'reason_description', 'status', 'created_at'];
    await chunkInsert(connection, 'refunds', refCols, dataset.refunds);

    // 8. Seed Inventory Movements
    console.log(`📊 Seeding ${dataset.inventory_movements.length} Inventory Movements...`);
    const movCols = ['id', 'merchant_id', 'product_id', 'movement_type', 'quantity', 'balance_after', 'reference_type', 'reference_id', 'notes', 'created_at'];
    await chunkInsert(connection, 'inventory_movements', movCols, dataset.inventory_movements);

    await connection.query('SET FOREIGN_KEY_CHECKS = 1');
    console.log('✅ All dataset records seeded successfully into MySQL!');
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
  } finally {
    if (connection) await connection.end();
  }
}

if (require.main === module) {
  seedDatabase();
}

module.exports = { seedDatabase };
